## Arewa Data Science Academy
### Deep Learning Cohort1.0

#### Name: Oladimeji Williams
#### Email: oladimejisewedowilliams@gmail.com
#### Title: Week 1 Solution

### Exercises Solution

#### Exercise 2a

In [1]:
# Import torch
import torch

#### Exercise 2b

In [2]:
# Create random tensor
random_tensor1 = torch.rand(7, 7)
print("Random Tensor (PyTorch):\n", random_tensor1)

Random Tensor (PyTorch):
 tensor([[0.6331, 0.3735, 0.4909, 0.9474, 0.0414, 0.0337, 0.7179],
        [0.4581, 0.1434, 0.6784, 0.0526, 0.5935, 0.0259, 0.6774],
        [0.4225, 0.6500, 0.1411, 0.6617, 0.0091, 0.9702, 0.7749],
        [0.5712, 0.8732, 0.5328, 0.4798, 0.4833, 0.9314, 0.0241],
        [0.6367, 0.7352, 0.4220, 0.4699, 0.5458, 0.4214, 0.7697],
        [0.3069, 0.8492, 0.8293, 0.0804, 0.9986, 0.9372, 0.4029],
        [0.0701, 0.8894, 0.6100, 0.5476, 0.1786, 0.2002, 0.0911]])


#### Exercise 3a

In [3]:
# Create another random tensor
random_tensor2 = torch.rand(1, 7)

#### Exercise 3b

In [4]:
# Perform matrix multiplication

random_tensor2_transposed = random_tensor2.T
result = torch.matmul(random_tensor1, random_tensor2_transposed)

# Print the tensors and the result
print("Random Tensor 1 (7x7):\n", random_tensor1)
print("\nRandom Tensor 2 (1x7):\n", random_tensor2)
print("\nRandom Tensor 2 Transposed (7x1):\n", random_tensor2_transposed)
print("\nResult of Matrix Multiplication (7x1):\n", result)


Random Tensor 1 (7x7):
 tensor([[0.6331, 0.3735, 0.4909, 0.9474, 0.0414, 0.0337, 0.7179],
        [0.4581, 0.1434, 0.6784, 0.0526, 0.5935, 0.0259, 0.6774],
        [0.4225, 0.6500, 0.1411, 0.6617, 0.0091, 0.9702, 0.7749],
        [0.5712, 0.8732, 0.5328, 0.4798, 0.4833, 0.9314, 0.0241],
        [0.6367, 0.7352, 0.4220, 0.4699, 0.5458, 0.4214, 0.7697],
        [0.3069, 0.8492, 0.8293, 0.0804, 0.9986, 0.9372, 0.4029],
        [0.0701, 0.8894, 0.6100, 0.5476, 0.1786, 0.2002, 0.0911]])

Random Tensor 2 (1x7):
 tensor([[0.8260, 0.2385, 0.3166, 0.5119, 0.4840, 0.6351, 0.8099]])

Random Tensor 2 Transposed (7x1):
 tensor([[0.8260],
        [0.2385],
        [0.3166],
        [0.5119],
        [0.4840],
        [0.6351],
        [0.8099]])

Result of Matrix Multiplication (3x1):
 tensor([[1.8752],
        [1.5066],
        [2.1354],
        [1.9392],
        [2.2306],
        [2.1647],
        [1.0308]])


#### Exercise 4a

In [5]:
# Set manual seed
torch.manual_seed(0)

#### Exercise 4b

In [6]:
# Create two random tensors
random_tensor1 = torch.rand(7, 7)
random_tensor2 = torch.rand(1, 7)

#### Exercise 4c

In [7]:
random_tensor2_transposed = random_tensor2.T
result = torch.matmul(random_tensor1, random_tensor2_transposed)
print("Random Tensor 1 (7x7):\n", random_tensor1)
print("\nRandom Tensor 2 (1x7):\n", random_tensor2)
print("\nRandom Tensor 2 Transposed (7x1):\n", random_tensor2_transposed)
print("\nResult of Matrix Multiplication (7x1):\n", result)

Random Tensor 1 (7x7):
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

Random Tensor 2 (1x7):
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

Random Tensor 2 Transposed (7x1):
 tensor([[0.4820],
        [0.8198],
        [0.9971],
        [0.6984],
        [0.5675],
        [0.8352],
        [0.2056]])

Result of Matrix Multiplication (7x1):
 tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


#### Exercise 5

In [8]:
# Set random seed on the GPU

if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    device = torch.device("cuda")
else:
    torch.manual_seed(0)
    device = torch.device("cpu")

#### Exercise 6a

In [9]:
# Set random seed
torch.manual_seed(1234)

#### Exercise 6b

In [10]:
# Check for access to GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


#### Exercise 6c

In [11]:
# Create two random tensors on GPU
tensor1 = torch.rand(2, 3).to(device)
tensor2 = torch.rand(2, 3).to(device)


print("Device:", device)
print("\nTensor 1:\n", tensor1)
print("\nTensor 2:\n", tensor2)

Device: cpu

Tensor 1:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

Tensor 2:
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


#### Exercise 7

In [12]:
# Perform matmul on tensor_A and tensor_B
tensor2_transposed = tensor2.T
result = torch.matmul(tensor1, tensor2_transposed)


print("Device:", device)
print("\nTensor 1:\n", tensor1)
print("\nTensor 2 (Transposed):\n", tensor2_transposed)
print("\nResult of Matrix Multiplication:\n", result)

Device: cpu

Tensor 1:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

Tensor 2 (Transposed):
 tensor([[0.0518, 0.3315],
        [0.4681, 0.7837],
        [0.6738, 0.5631]])

Result of Matrix Multiplication:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


#### Exercise 8a

In [13]:
# Find max
max_value = result.max()

print("\nMaximum value in the result tensor:", max_value.item())


Maximum value in the result tensor: 0.5617256760597229


#### Exercise 8b

In [14]:
# Find min
min_value = result.min()

print("\nMinimum value in the result tensor:", min_value.item())


Minimum value in the result tensor: 0.3647301495075226


#### Exercise 9a

In [15]:
# Find arg max
arg_max_index = result.argmax()

print("\nIndex of the maximum value in the result tensor:", arg_max_index.item())


Index of the maximum value in the result tensor: 3


#### Exercise 9b

In [16]:
# Find arg min
arg_min_index = result.argmin()

print("\nIndex of the minimum value in the result tensor:", arg_min_index.item())



Index of the minimum value in the result tensor: 0


#### Exercise 10a

In [17]:
# Set seed
torch.manual_seed(7)

#### Exercise 10b

In [18]:
# Create random tensor
tensor1 = torch.randn(1, 1, 1, 10)

#### Exercise 10c

In [19]:
# Remove single dimensions
tensor2 = tensor1.squeeze()

#### Exercise 10d

In [20]:
# Print out tensors and their shapes
print("First tensor:", tensor1)
print("Shape of first tensor:", tensor1.shape)
print("Second tensor:", tensor2)
print("Shape of second tensor:", tensor2.shape)

First tensor: tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])
Shape of first tensor: torch.Size([1, 1, 1, 10])
Second tensor: tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])
Shape of second tensor: torch.Size([10])


### Additional Exercises Solution

**NOTE: NOT TO BE INCLUDED IN SUBMISSION FILE**\
HOW TO SUBMIT NOTES:
1. Clone the repository
```bash
git clone https://github.com/arewadataScience/ArewaDS-Deep-Learning.git
```
2. Save each week's notebooks in this subfolder `exercise_submissions`
3. Use the naming convension `week_{num}_solution.ipynb` e.g. `week_1_solution.ipynb`
4. Please, make sure all the clear runs without errors and keep cell outputs before submission.


SUBMIT ASSIGNMENT HERE: [CLICK ME ▶️](https://forms.gle/876vi4aNoFf4A2mU7)